name: Run benchmarks

on:
  pull_request:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: crystal-lang/install-crystal@v1
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-env -f '<nixpkgs>' -iA wrk rustc cargo go nodejs nodePackages.npm
    - run: crystal run.cr